main:
  - name: Who Am I
    url: /WhoAmI/
    weight: 200

  - name: Biography
    url: none
    weight: 330
  - parent: Biography
    name: Education
    url: /Biography/Education/
    weight: 340
  - parent: Biography
    name: Awards
    url: /Biography/Awards/
    weight: 350

  - name: Projects
    url: project
    weight: 430
  - parent: Projects
    name: Project in Progress
    url: /project/ing/
    weight: 440
  - parent: Projects
    name: Finished Project
    url: /project/ed/
    weight: 450

  - name: Blog
    url: publication
    weight: 500
  - parent: Blog
    name: Study
    url: /bulletin/study
    weight: 510
  - parent: Blog
    name: Reflection on Life
    url: /bulletin/life
    weight: 520

  - name: Contact
    url: contact
    weight: 800
