
main:
  - identifier: about
    name: "소개"
    url: "/#about"
    weight: 10
  - identifier: projects
    name: "프로젝트"
    url: "/#projects"
    weight: 20
  - identifier: experience
    name: "경험"
    url: "/#experience"
    weight: 30
  - identifier: contact
    name: "연락처"
    url: "/#contact"
    weight: 40
