# Appearance settings
appearance:
  theme_night: custom
  theme_day: custom
  font: native
  font_size: L


# Open Graph and Social Media settings
social_media:
  facebook:
    app_id: ''
    page_id: ''
  twitter:
    card_type: summary_large_image
    site: '@GetResearchDev'

# Site header settings
header:
  navbar:
    enable: true
    align: c
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    show_theme_chooser: true
    show_translations: true
    highlight_active_link: false
    button:
      enable: true
      text: 백정렬
      url: "https://bjl5029.github.io/"

# Site footer settings
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization settings
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features settings
features:
  syntax_highlighter:
    enable: true  # Enable syntax highlighting
    extra_languages:
      - r
      - latex
  math:
    enable: false  # Math rendering
  privacy_pack:
    enable: false  # Privacy pack
  repository:
    url: 'https://github.com/bjl5029/bjl5029.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy  # Search provider
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions settings
extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style for publications
publications:
  date_format: January 2006
  citation_style: apa

# Personal information
name: 백정렬
role: 학생
organization: 전북대학교 컴퓨터인공지능학부
organization_url: 'https://csai.jbnu.ac.kr/csai/index.do'
email: 'bjl5029@gmail.com'


